### ISSUE TITLE
Just how to run the test?

### ISSUE THREAD

**Issue by whucsu** [TS-CUBED/CirculatorySystemModels.jl#22]
sorry for new in Julia, and how to run the test in this code? 
thanks~

**Comment by TS-CUBED** [comment]
The tests are meant to run automatically on github, but if you want to run them yourself you'll need to:

1. checkout the whole repository (in addition to adding the module to your Julia environment)
2. add the required modules to your Julia environment:
    - CirculatorySystemModels
    - ModelingToolkit
    - DifferentialEquations
    - Test
    - CSV
    - DataFrames
3. Run the tests in the test directory:
    `julia runtests.jl`

That should work.

Also check out the docs: https://ts-cubed.github.io/CirculatorySystemModels.jl/dev/

**Comment by whucsu** [comment]
yes，it works.  Is there any user guide on the topic with more details ?
Wish the team can do some more application examples. 
best wishes.

**Comment by TS-CUBED** [comment]
We are working on more examples and tips and tricks specific for CSM. 

In the meantime, since this is built on ModelingToolkit.jl and the wider SciML framework, their documentation may help you understand how it all works under the hood. 

If you drop me a PM, and give me some details on what you are trying to do, then I'll see if I can help you more concretely.

**Comment by whucsu** [comment]
there are two teams I have found using LPM for solving the problems in medical science.
One,Prof. Zahra Keshavarz-Motamed in McMaster University Hamilton, they used Matlab,with the paper "An ultrasound-exclusive non-invasive computational diagnostic framework for personalized cardiology of aortic valve stenosis" on: https://pubmed.ncbi.nlm.nih.gov/37060702/;

Second, Prof. Ryno Laubscher, using Julia, with the paper "Non-invasive estimation of left ventricle elastance using a multi-compartment lumped parameter model and gradient-based optimization with forward-mode automatic differentiation" on https://arxiv.org/abs/2205.12330.

Maybe there are some other topics, but this two, with the example shi_hose 2009, can solve some appplication in the clinical use.

Best wishes.
